import 'app_database.dart';

List<ExercisesCompanion> get initialExercises {
  return [
    ExercisesCompanion.insert(
      name: 'Sentadilla con peso corporal',
      description:
          'Sentadilla realizada utilizando únicamente el peso corporal.',
      primaryMuscle: 'quadriceps',
      difficulty: 'beginner',
      movementPattern: 'squat',
      exerciseType: 'bodyweight',
      technique: 'Mantener el tronco estable y controlar la fase de descenso.',
      commonMistakes: 'Colapsar las rodillas hacia dentro o perder el control del descenso.',
      considerations:
          'Adaptar la profundidad al nivel de movilidad y experiencia.',
      instructions: 'Coloca los pies a una anchura cómoda, desciende flexionando cadera y rodillas y vuelve a la posición inicial.',
    ),
    ExercisesCompanion.insert(
      name: 'Sentadilla goblet',
      description:
          'Sentadilla sosteniendo una mancuerna o pesa rusa frente al pecho.',
      primaryMuscle: 'quadriceps',
      difficulty: 'beginner',
      movementPattern: 'squat',
      exerciseType: 'strength',
      technique:
          'Mantener la carga próxima al torso y controlar el movimiento.',
      commonMistakes: 'Inclinar excesivamente el torso o perder la trayectoria de las rodillas.',
      considerations: 'Utilizar una carga que permita realizar todas las repeticiones con control.',
      instructions: 'Sostén la carga frente al pecho, desciende controladamente y extiende las piernas para regresar.',
    ),
    ExercisesCompanion.insert(
      name: 'Sentadilla con barra',
      description:
          'Sentadilla con barra apoyada sobre la parte superior de la espalda.',
      primaryMuscle: 'quadriceps',
      difficulty: 'intermediate',
      movementPattern: 'squat',
      exerciseType: 'strength',
      technique:
          'Mantener estabilidad del tronco y una trayectoria consistente.',
      commonMistakes:
          'Perder la posición de la espalda o utilizar una carga excesiva.',
      considerations: 'Priorizar la técnica antes de aumentar la carga.',
      instructions: 'Coloca la barra de forma segura, desciende flexionando cadera y rodillas y vuelve a extender.',
    ),
    ExercisesCompanion.insert(
      name: 'Prensa de piernas',
      description:
          'Ejercicio para tren inferior realizado en máquina de prensa.',
      primaryMuscle: 'quadriceps',
      difficulty: 'beginner',
      movementPattern: 'squat',
      exerciseType: 'strength',
      technique: 'Mantener los pies estables y controlar el recorrido.',
      commonMistakes:
          'Bloquear las rodillas o despegar la pelvis del respaldo.',
      considerations: 'Utilizar un rango de movimiento cómodo y controlado.',
      instructions: 'Coloca los pies en la plataforma, flexiona rodillas para descender y empuja para regresar.',
    ),
    ExercisesCompanion.insert(
      name: 'Zancadas',
      description:
          'Movimiento unilateral de piernas realizado mediante pasos alternos.',
      primaryMuscle: 'quadriceps',
      difficulty: 'beginner',
      movementPattern: 'lunge',
      exerciseType: 'bodyweight',
      technique: 'Mantener equilibrio y controlar la alineación de la pierna delantera.',
      commonMistakes:
          'Perder el equilibrio o dejar caer la rodilla sin control.',
      considerations: 'Comenzar sin carga hasta dominar el patrón.',
      instructions: 'Da un paso al frente, desciende de forma controlada y empuja con la pierna delantera para volver.',
    ),
    ExercisesCompanion.insert(
      name: 'Sentadilla dividida',
      description:
          'Ejercicio unilateral con una pierna adelantada y otra detrás.',
      primaryMuscle: 'quadriceps',
      difficulty: 'beginner',
      movementPattern: 'lunge',
      exerciseType: 'bodyweight',
      technique: 'Mantener estabilidad de pelvis y rodilla durante todo el movimiento.',
      commonMistakes: 'Acortar demasiado la posición o perder el equilibrio.',
      considerations:
          'Usar apoyo externo si se necesita mejorar la estabilidad.',
      instructions: 'Adopta una posición escalonada, flexiona ambas rodillas y vuelve a extender.',
    ),
    ExercisesCompanion.insert(
      name: 'Step-up',
      description:
          'Subida controlada a una plataforma utilizando una pierna a la vez.',
      primaryMuscle: 'quadriceps',
      difficulty: 'beginner',
      movementPattern: 'lunge',
      exerciseType: 'bodyweight',
      technique: 'Impulsarse principalmente con la pierna que está sobre la plataforma.',
      commonMistakes: 'Usar demasiado impulso de la pierna trasera.',
      considerations: 'Elegir una plataforma estable y de altura adecuada.',
      instructions: 'Coloca un pie sobre la plataforma, empuja para subir y desciende de forma controlada.',
    ),
    ExercisesCompanion.insert(
      name: 'Peso muerto rumano',
      description:
          'Movimiento de bisagra de cadera enfocado en la cadena posterior.',
      primaryMuscle: 'hamstrings',
      difficulty: 'intermediate',
      movementPattern: 'hinge',
      exerciseType: 'strength',
      technique: 'Mantener la carga cercana al cuerpo y desplazar la cadera hacia atrás.',
      commonMistakes:
          'Redondear la espalda o convertir el movimiento en una sentadilla.',
      considerations: 'Usar una carga moderada hasta dominar la bisagra.',
      instructions: 'Desde una posición erguida, lleva la cadera hacia atrás con las piernas ligeramente flexionadas y regresa.',
    ),
    ExercisesCompanion.insert(
      name: 'Peso muerto convencional',
      description: 'Levantamiento desde el suelo mediante una bisagra de cadera y extensión de piernas.',
      primaryMuscle: 'glutes',
      difficulty: 'intermediate',
      movementPattern: 'hinge',
      exerciseType: 'strength',
      technique: 'Mantener la carga próxima al cuerpo y una posición estable del tronco.',
      commonMistakes:
          'Separar demasiado la carga del cuerpo o iniciar con la espalda.',
      considerations: 'Aprender la técnica con cargas ligeras.',
      instructions: 'Colócate frente a la barra, prepara el tronco, empuja el suelo y extiende cadera y rodillas.',
    ),
    ExercisesCompanion.insert(
      name: 'Hip thrust',
      description: 'Extensión de cadera realizada con apoyo de la espalda.',
      primaryMuscle: 'glutes',
      difficulty: 'beginner',
      movementPattern: 'hinge',
      exerciseType: 'strength',
      technique: 'Realizar una extensión de cadera controlada sin hiperextender la espalda.',
      commonMistakes: 'Arquear excesivamente la zona lumbar.',
      considerations: 'Comenzar con peso corporal antes de progresar.',
      instructions: 'Apoya la parte superior de la espalda, coloca los pies firmes y extiende la cadera hasta quedar alineado.',
    ),
    ExercisesCompanion.insert(
      name: 'Puente de glúteos',
      description: 'Extensión de cadera desde el suelo.',
      primaryMuscle: 'glutes',
      difficulty: 'beginner',
      movementPattern: 'hinge',
      exerciseType: 'bodyweight',
      technique: 'Contraer los glúteos al llegar a la parte superior.',
      commonMistakes: 'Elevarse mediante hiperextensión lumbar.',
      considerations: 'Mantener el abdomen activo durante el movimiento.',
      instructions: 'Tumbado boca arriba, flexiona las rodillas, empuja con los pies y eleva la cadera.',
    ),
    ExercisesCompanion.insert(
      name: 'Curl femoral',
      description:
          'Flexión de rodilla realizada en máquina para los isquiotibiales.',
      primaryMuscle: 'hamstrings',
      difficulty: 'beginner',
      movementPattern: 'knee_flexion',
      exerciseType: 'strength',
      technique: 'Realizar el recorrido completo de manera controlada.',
      commonMistakes: 'Utilizar impulso o levantar la pelvis del soporte.',
      considerations: 'Ajustar correctamente la máquina.',
      instructions: 'Coloca las piernas en el soporte, flexiona las rodillas y regresa lentamente.',
    ),
    ExercisesCompanion.insert(
      name: 'Extensión de rodilla',
      description: 'Extensión de rodilla realizada en máquina.',
      primaryMuscle: 'quadriceps',
      difficulty: 'beginner',
      movementPattern: 'knee_extension',
      exerciseType: 'strength',
      technique: 'Controlar especialmente el descenso.',
      commonMistakes: 'Usar cargas excesivas o movimientos bruscos.',
      considerations: 'Ajustar correctamente la máquina.',
      instructions: 'Desde una posición estable, extiende las rodillas y regresa lentamente.',
    ),
    ExercisesCompanion.insert(
      name: 'Elevación de pantorrillas',
      description:
          'Elevación del talón para trabajar la musculatura de la pantorrilla.',
      primaryMuscle: 'calves',
      difficulty: 'beginner',
      movementPattern: 'calf_raise',
      exerciseType: 'strength',
      technique: 'Buscar un recorrido controlado y completo.',
      commonMistakes: 'Realizar rebotes rápidos.',
      considerations: 'Utilizar apoyo estable.',
      instructions: 'Desde una posición estable, eleva los talones y desciende lentamente.',
    ),
    ExercisesCompanion.insert(
      name: 'Press de banca',
      description: 'Empuje horizontal realizado con barra.',
      primaryMuscle: 'chest',
      difficulty: 'intermediate',
      movementPattern: 'horizontal_push',
      exerciseType: 'strength',
      technique: 'Mantener control de la barra y estabilidad de hombros.',
      commonMistakes: 'Rebotar la barra o perder la posición de los hombros.',
      considerations:
          'Utilizar un soporte seguro y asistencia cuando corresponda.',
      instructions: 'Tumbado en el banco, baja la barra controladamente hacia el pecho y empuja hasta extender los brazos.',
    ),
    ExercisesCompanion.insert(
      name: 'Press inclinado con mancuernas',
      description: 'Empuje inclinado utilizando mancuernas.',
      primaryMuscle: 'chest',
      difficulty: 'intermediate',
      movementPattern: 'horizontal_push',
      exerciseType: 'strength',
      technique: 'Mantener una trayectoria controlada y simétrica.',
      commonMistakes:
          'Descender sin control o mover excesivamente los hombros.',
      considerations: 'Elegir una inclinación y carga adecuadas.',
      instructions: 'Apoya la espalda en un banco inclinado, baja las mancuernas y empuja hacia arriba.',
    ),
    ExercisesCompanion.insert(
      name: 'Flexiones',
      description: 'Empuje horizontal utilizando el peso corporal.',
      primaryMuscle: 'chest',
      difficulty: 'beginner',
      movementPattern: 'horizontal_push',
      exerciseType: 'bodyweight',
      technique: 'Mantener el cuerpo alineado durante el movimiento.',
      commonMistakes: 'Dejar caer la cadera o separar demasiado los codos.',
      considerations: 'Modificar el apoyo para adaptar la dificultad.',
      instructions: 'Desde una posición de plancha, flexiona los codos para acercar el pecho al suelo y empuja para volver.',
    ),
    ExercisesCompanion.insert(
      name: 'Press militar con mancuernas',
      description: 'Empuje vertical utilizando mancuernas.',
      primaryMuscle: 'shoulders',
      difficulty: 'beginner',
      movementPattern: 'vertical_push',
      exerciseType: 'strength',
      technique: 'Mantener el tronco estable y controlar el recorrido.',
      commonMistakes: 'Compensar mediante una inclinación excesiva del tronco.',
      considerations: 'Elegir una carga que permita mantener estabilidad.',
      instructions: 'Coloca las mancuernas a la altura de los hombros y empújalas hacia arriba.',
    ),
    ExercisesCompanion.insert(
      name: 'Elevaciones laterales',
      description:
          'Ejercicio de aislamiento para la musculatura lateral del hombro.',
      primaryMuscle: 'shoulders',
      difficulty: 'beginner',
      movementPattern: 'shoulder_abduction',
      exerciseType: 'strength',
      technique: 'Utilizar un movimiento controlado y una carga ligera.',
      commonMistakes: 'Balancear el cuerpo o utilizar demasiado peso.',
      considerations: 'Evitar movimientos bruscos.',
      instructions: 'Eleva los brazos lateralmente hasta una posición cómoda y desciende lentamente.',
    ),
    ExercisesCompanion.insert(
      name: 'Fondos en paralelas',
      description: 'Empuje de tren superior realizado en paralelas.',
      primaryMuscle: 'triceps',
      difficulty: 'intermediate',
      movementPattern: 'vertical_push',
      exerciseType: 'strength',
      technique: 'Controlar el descenso y mantener estabilidad de hombros.',
      commonMistakes:
          'Descender sin control o perder la posición de los hombros.',
      considerations:
          'Utilizar asistencia si todavía no se domina el movimiento.',
      instructions: 'Sujétate a las paralelas, flexiona los codos para descender y empuja para volver.',
    ),
    ExercisesCompanion.insert(
      name: 'Jalón al pecho',
      description: 'Tirón vertical realizado en polea.',
      primaryMuscle: 'latissimus',
      difficulty: 'beginner',
      movementPattern: 'vertical_pull',
      exerciseType: 'strength',
      technique: 'Mantener el tronco estable y llevar los codos hacia abajo.',
      commonMistakes:
          'Tirar con impulso del cuerpo o llevar la barra detrás de la cabeza.',
      considerations: 'Utilizar una carga controlable.',
      instructions: 'Agarra la barra, inicia el movimiento con los codos hacia abajo y vuelve lentamente.',
    ),
    ExercisesCompanion.insert(
      name: 'Remo sentado en polea',
      description: 'Tirón horizontal realizado en polea baja.',
      primaryMuscle: 'upper_back',
      difficulty: 'beginner',
      movementPattern: 'horizontal_pull',
      exerciseType: 'strength',
      technique: 'Mantener el pecho estable y acercar los codos al cuerpo.',
      commonMistakes: 'Balancear el torso o encoger excesivamente los hombros.',
      considerations: 'Controlar el retorno de la carga.',
      instructions: 'Desde una posición estable, tira del agarre hacia el torso y regresa lentamente.',
    ),
    ExercisesCompanion.insert(
      name: 'Remo con mancuerna',
      description: 'Tirón horizontal unilateral realizado con mancuerna.',
      primaryMuscle: 'upper_back',
      difficulty: 'beginner',
      movementPattern: 'horizontal_pull',
      exerciseType: 'strength',
      technique: 'Mantener una base estable y controlar la trayectoria.',
      commonMistakes: 'Rotar excesivamente el torso.',
      considerations: 'Usar apoyo cuando sea necesario.',
      instructions: 'Apóyate sobre una superficie estable, lleva la mancuerna hacia la cadera y desciende lentamente.',
    ),
    ExercisesCompanion.insert(
      name: 'Dominadas asistidas',
      description:
          'Tirón vertical para trabajar espalda y brazos con asistencia.',
      primaryMuscle: 'latissimus',
      difficulty: 'intermediate',
      movementPattern: 'vertical_pull',
      exerciseType: 'strength',
      technique: 'Evitar balanceos y controlar la fase de descenso.',
      commonMistakes: 'Usar demasiado impulso.',
      considerations: 'Ajustar la asistencia al nivel del usuario.',
      instructions: 'Sujétate a la barra, realiza el tirón con control y desciende lentamente.',
    ),
    ExercisesCompanion.insert(
      name: 'Face pull',
      description: 'Tirón hacia el rostro para trabajar la musculatura posterior del hombro y espalda alta.',
      primaryMuscle: 'rear_delts',
      difficulty: 'beginner',
      movementPattern: 'horizontal_pull',
      exerciseType: 'strength',
      technique: 'Mantener los codos abiertos y controlar el recorrido.',
      commonMistakes: 'Usar una carga excesiva o compensar con el torso.',
      considerations: 'Priorizar el control del movimiento.',
      instructions: 'Tira del cable hacia el rostro separando las manos y regresa lentamente.',
    ),
    ExercisesCompanion.insert(
      name: 'Curl de bíceps',
      description: 'Flexión de codo realizada con mancuernas.',
      primaryMuscle: 'biceps',
      difficulty: 'beginner',
      movementPattern: 'elbow_flexion',
      exerciseType: 'strength',
      technique: 'Mantener los codos estables durante todo el movimiento.',
      commonMistakes: 'Balancear el torso para mover la carga.',
      considerations: 'Utilizar una carga que permita controlar la bajada.',
      instructions: 'Desde una posición estable, flexiona los codos para elevar las mancuernas y desciende lentamente.',
    ),
    ExercisesCompanion.insert(
      name: 'Curl martillo',
      description:
          'Curl con agarre neutro para bíceps y musculatura del antebrazo.',
      primaryMuscle: 'biceps',
      difficulty: 'beginner',
      movementPattern: 'elbow_flexion',
      exerciseType: 'strength',
      technique: 'Mantener las muñecas neutras y los codos estables.',
      commonMistakes: 'Mover excesivamente los hombros.',
      considerations: 'Evitar balanceos.',
      instructions: 'Mantén las palmas enfrentadas, flexiona los codos y regresa lentamente.',
    ),
    ExercisesCompanion.insert(
      name: 'Extensión de tríceps en polea',
      description: 'Extensión de codo realizada en polea.',
      primaryMuscle: 'triceps',
      difficulty: 'beginner',
      movementPattern: 'elbow_extension',
      exerciseType: 'strength',
      technique: 'Mantener los codos relativamente fijos.',
      commonMistakes: 'Mover los hombros para generar impulso.',
      considerations: 'Seleccionar una carga controlable.',
      instructions: 'Sujeta el agarre, extiende los codos hacia abajo y regresa de forma controlada.',
    ),
    ExercisesCompanion.insert(
      name: 'Extensión de tríceps por encima de la cabeza',
      description:
          'Extensión de codo realizada con la carga por encima de la cabeza.',
      primaryMuscle: 'triceps',
      difficulty: 'beginner',
      movementPattern: 'elbow_extension',
      exerciseType: 'strength',
      technique: 'Mantener el tronco estable y los codos controlados.',
      commonMistakes: 'Abrir excesivamente los codos o arquear la espalda.',
      considerations: 'Usar una carga moderada.',
      instructions: 'Coloca la carga sobre la cabeza, flexiona los codos y extiéndelos para regresar.',
    ),
    ExercisesCompanion.insert(
      name: 'Plancha',
      description: 'Ejercicio isométrico de estabilidad del tronco.',
      primaryMuscle: 'core',
      difficulty: 'beginner',
      movementPattern: 'core_anti_extension',
      exerciseType: 'core',
      technique: 'Mantener una línea estable desde hombros hasta cadera.',
      commonMistakes: 'Dejar caer la cadera o elevarla demasiado.',
      considerations: 'Reducir la duración si se pierde la posición.',
      instructions:
          'Apoya antebrazos y pies, activa el tronco y mantén la posición.',
    ),
    ExercisesCompanion.insert(
      name: 'Dead bug',
      description:
          'Ejercicio de control del tronco y coordinación de extremidades.',
      primaryMuscle: 'core',
      difficulty: 'beginner',
      movementPattern: 'core_anti_extension',
      exerciseType: 'core',
      technique: 'Mantener la zona lumbar estable durante el movimiento.',
      commonMistakes:
          'Mover las extremidades más allá de la capacidad de control.',
      considerations:
          'Reducir el rango de movimiento si se pierde estabilidad.',
      instructions: 'Desde tumbado boca arriba, mueve brazo y pierna contrarios manteniendo el tronco estable.',
    ),
    ExercisesCompanion.insert(
      name: 'Bird dog',
      description:
          'Ejercicio de estabilidad del tronco con movimiento contralateral.',
      primaryMuscle: 'core',
      difficulty: 'beginner',
      movementPattern: 'core_anti_rotation',
      exerciseType: 'core',
      technique: 'Evitar la rotación del tronco.',
      commonMistakes: 'Elevar demasiado las extremidades o mover la pelvis.',
      considerations: 'Realizar movimientos lentos.',
      instructions: 'Desde cuatro apoyos, extiende brazo y pierna contrarios y regresa controladamente.',
    ),
    ExercisesCompanion.insert(
      name: 'Crunch abdominal',
      description: 'Flexión controlada del tronco para trabajar la musculatura abdominal.',
      primaryMuscle: 'core',
      difficulty: 'beginner',
      movementPattern: 'core_flexion',
      exerciseType: 'core',
      technique: 'Realizar una flexión controlada sin tirar del cuello.',
      commonMistakes:
          'Impulsarse con las manos o realizar movimientos bruscos.',
      considerations: 'Detenerse si aparece molestia.',
      instructions: 'Tumbado boca arriba, flexiona el tronco de forma controlada y regresa lentamente.',
    ),
    ExercisesCompanion.insert(
      name: 'Pallof press',
      description:
          'Ejercicio de resistencia a la rotación realizado con cable o banda.',
      primaryMuscle: 'core',
      difficulty: 'beginner',
      movementPattern: 'core_anti_rotation',
      exerciseType: 'core',
      technique: 'Mantener el torso estable mientras se aleja el agarre.',
      commonMistakes: 'Rotar el tronco siguiendo la resistencia.',
      considerations: 'Ajustar la resistencia al nivel de control.',
      instructions: 'Colócate de lado a la resistencia, lleva el agarre al centro y extiende los brazos sin rotar.',
    ),
    ExercisesCompanion.insert(
      name: 'Mountain climbers',
      description: 'Ejercicio dinámico que combina estabilidad del tronco y movimiento de piernas.',
      primaryMuscle: 'core',
      difficulty: 'intermediate',
      movementPattern: 'locomotion',
      exerciseType: 'cardio',
      technique:
          'Mantener las manos estables y controlar la posición de la cadera.',
      commonMistakes: 'Rebotar o elevar demasiado la cadera.',
      considerations: 'Reducir la velocidad para mantener la técnica.',
      instructions: 'Desde una posición de plancha, lleva una rodilla hacia el pecho y alterna de forma controlada.',
    ),
    ExercisesCompanion.insert(
      name: 'Farmer walk',
      description: 'Desplazamiento transportando una carga en ambas manos.',
      primaryMuscle: 'forearms',
      difficulty: 'beginner',
      movementPattern: 'carry',
      exerciseType: 'strength',
      technique: 'Mantener postura erguida y pasos controlados.',
      commonMistakes: 'Encoger excesivamente los hombros o inclinar el torso.',
      considerations: 'Utilizar un espacio seguro para caminar.',
      instructions: 'Sujeta las cargas a los lados, mantén el tronco estable y camina durante la distancia indicada.',
    ),
    ExercisesCompanion.insert(
      name: 'Burpee',
      description: 'Movimiento dinámico de cuerpo completo.',
      primaryMuscle: 'full_body',
      difficulty: 'intermediate',
      movementPattern: 'locomotion',
      exerciseType: 'cardio',
      technique: 'Priorizar el control y adaptar la velocidad al nivel.',
      commonMistakes: 'Realizar los cambios de posición sin control.',
      considerations:
          'Utilizar una variante más sencilla cuando sea necesario.',
      instructions: 'Desde de pie, baja a una posición de apoyo, vuelve a incorporarte y finaliza extendiendo el cuerpo.',
    ),
  ];
}
