import 'app_database.dart';

List<ExercisesCompanion> get initialExercises {
  return [
    ExercisesCompanion.insert(
      name: 'Sentadilla con peso corporal',
      description:
          'Sentadilla realizada utilizando únicamente el peso corporal.',
      primaryMuscle: 'quadriceps',
      difficulty: 'beginner',
      movementPattern: 'squat',
      exerciseType: 'bodyweight',
      technique: 'Mantener el tronco estable y controlar la fase de descenso.',
      commonMistakes: 'Colapsar las rodillas hacia dentro o perder el control del descenso.',
      considerations:
          'Adaptar la profundidad al nivel de movilidad y experiencia.',
      instructions: 'Coloca los pies a una anchura cómoda, desciende flexionando cadera y rodillas y vuelve a la posición inicial.',
    ),
    ExercisesCompanion.insert(
      name: 'Sentadilla goblet',
      description:
          'Sentadilla sosteniendo una mancuerna o pesa rusa frente al pecho.',
      primaryMuscle: 'quadriceps',
      difficulty: 'beginner',
      movementPattern: 'squat',
      exerciseType: 'strength',
      technique:
          'Mantener la carga próxima al torso y controlar el movimiento.',
      commonMistakes: 'Inclinar excesivamente el torso o perder la trayectoria de las rodillas.',
      considerations: 'Utilizar una carga que permita realizar todas las repeticiones con control.',
      instructions: 'Sostén la carga frente al pecho, desciende controladamente y extiende las piernas para regresar.',
    ),
    ExercisesCompanion.insert(
      name: 'Sentadilla con barra',
      description:
          'Sentadilla con barra apoyada sobre la parte superior de la espalda.',
      primaryMuscle: 'quadriceps',
      difficulty: 'intermediate',
      movementPattern: 'squat',
      exerciseType: 'strength',
      technique:
          'Mantener estabilidad del tronco y una trayectoria consistente.',
      commonMistakes:
          'Perder la posición de la espalda o utilizar una carga excesiva.',
      considerations: 'Priorizar la técnica antes de aumentar la carga.',
      instructions: 'Coloca la barra de forma segura, desciende flexionando cadera y rodillas y vuelve a extender.',
    ),
    ExercisesCompanion.insert(
      name: 'Prensa de piernas',
      description:
          'Ejercicio para tren inferior realizado en máquina de prensa.',
      primaryMuscle: 'quadriceps',
      difficulty: 'beginner',
      movementPattern: 'squat',
      exerciseType: 'strength',
      technique: 'Mantener los pies estables y controlar el recorrido.',
      commonMistakes:
          'Bloquear las rodillas o despegar la pelvis del respaldo.',
      considerations: 'Utilizar un rango de movimiento cómodo y controlado.',
      instructions: 'Coloca los pies en la plataforma, flexiona rodillas para descender y empuja para regresar.',
    ),
    ExercisesCompanion.insert(
      name: 'Zancadas',
      description:
          'Movimiento unilateral de piernas realizado mediante pasos alternos.',
      primaryMuscle: 'quadriceps',
      difficulty: 'beginner',
      movementPattern: 'lunge',
      exerciseType: 'bodyweight',
      technique: 'Mantener equilibrio y controlar la alineación de la pierna delantera.',
      commonMistakes:
          'Perder el equilibrio o dejar caer la rodilla sin control.',
      considerations: 'Comenzar sin carga hasta dominar el patrón.',
      instructions: 'Da un paso al frente, desciende de forma controlada y empuja con la pierna delantera para volver.',
    ),
    ExercisesCompanion.insert(
      name: 'Sentadilla dividida',
      description:
          'Ejercicio unilateral con una pierna adelantada y otra detrás.',
      primaryMuscle: 'quadriceps',
      difficulty: 'beginner',
      movementPattern: 'lunge',
      exerciseType: 'bodyweight',
      technique: 'Mantener estabilidad de pelvis y rodilla durante todo el movimiento.',
      commonMistakes: 'Acortar demasiado la posición o perder el equilibrio.',
      considerations:
          'Usar apoyo externo si se necesita mejorar la estabilidad.',
      instructions: 'Adopta una posición escalonada, flexiona ambas rodillas y vuelve a extender.',
    ),
    ExercisesCompanion.insert(
      name: 'Step-up',
      description:
          'Subida controlada a una plataforma utilizando una pierna a la vez.',
      primaryMuscle: 'quadriceps',
      difficulty: 'beginner',
      movementPattern: 'lunge',
      exerciseType: 'bodyweight',
      technique: 'Impulsarse principalmente con la pierna que está sobre la plataforma.',
      commonMistakes: 'Usar demasiado impulso de la pierna trasera.',
      considerations: 'Elegir una plataforma estable y de altura adecuada.',
      instructions: 'Coloca un pie sobre la plataforma, empuja para subir y desciende de forma controlada.',
    ),
    ExercisesCompanion.insert(
      name: 'Peso muerto rumano',
      description:
          'Movimiento de bisagra de cadera enfocado en la cadena posterior.',
      primaryMuscle: 'hamstrings',
      difficulty: 'intermediate',
      movementPattern: 'hinge',
      exerciseType: 'strength',
      technique: 'Mantener la carga cercana al cuerpo y desplazar la cadera hacia atrás.',
      commonMistakes:
          'Redondear la espalda o convertir el movimiento en una sentadilla.',
      considerations: 'Usar una carga moderada hasta dominar la bisagra.',
      instructions: 'Desde una posición erguida, lleva la cadera hacia atrás con las piernas ligeramente flexionadas y regresa.',
    ),
    ExercisesCompanion.insert(
      name: 'Peso muerto convencional',
      description: 'Levantamiento desde el suelo mediante una bisagra de cadera y extensión de piernas.',
      primaryMuscle: 'glutes',
      difficulty: 'intermediate',
      movementPattern: 'hinge',
      exerciseType: 'strength',
      technique: 'Mantener la carga próxima al cuerpo y una posición estable del tronco.',
      commonMistakes:
          'Separar demasiado la carga del cuerpo o iniciar con la espalda.',
      considerations: 'Aprender la técnica con cargas ligeras.',
      instructions: 'Colócate frente a la barra, prepara el tronco, empuja el suelo y extiende cadera y rodillas.',
    ),
    ExercisesCompanion.insert(
      name: 'Hip thrust',
      description: 'Extensión de cadera realizada con apoyo de la espalda.',
      primaryMuscle: 'glutes',
      difficulty: 'beginner',
      movementPattern: 'hinge',
      exerciseType: 'strength',
      technique: 'Realizar una extensión de cadera controlada sin hiperextender la espalda.',
      commonMistakes: 'Arquear excesivamente la zona lumbar.',
      considerations: 'Comenzar con peso corporal antes de progresar.',
      instructions: 'Apoya la parte superior de la espalda, coloca los pies firmes y extiende la cadera hasta quedar alineado.',
    ),
    ExercisesCompanion.insert(
      name: 'Puente de glúteos',
      description: 'Extensión de cadera desde el suelo.',
      primaryMuscle: 'glutes',
      difficulty: 'beginner',
      movementPattern: 'hinge',
      exerciseType: 'bodyweight',
      technique: 'Contraer los glúteos al llegar a la parte superior.',
      commonMistakes: 'Elevarse mediante hiperextensión lumbar.',
      considerations: 'Mantener el abdomen activo durante el movimiento.',
      instructions: 'Tumbado boca arriba, flexiona las rodillas, empuja con los pies y eleva la cadera.',
    ),
    ExercisesCompanion.insert(
      name: 'Curl femoral',
      description:
          'Flexión de rodilla realizada en máquina para los isquiotibiales.',
      primaryMuscle: 'hamstrings',
      difficulty: 'beginner',
      movementPattern: 'knee_flexion',
      exerciseType: 'strength',
      technique: 'Realizar el recorrido completo de manera controlada.',
      commonMistakes: 'Utilizar impulso o levantar la pelvis del soporte.',
      considerations: 'Ajustar correctamente la máquina.',
      instructions: 'Coloca las piernas en el soporte, flexiona las rodillas y regresa lentamente.',
    ),
    ExercisesCompanion.insert(
      name: 'Extensión de rodilla',
      description: 'Extensión de rodilla realizada en máquina.',
      primaryMuscle: 'quadriceps',
      difficulty: 'beginner',
      movementPattern: 'knee_extension',
      exerciseType: 'strength',
      technique: 'Controlar especialmente el descenso.',
      commonMistakes: 'Usar cargas excesivas o movimientos bruscos.',
      considerations: 'Ajustar correctamente la máquina.',
      instructions: 'Desde una posición estable, extiende las rodillas y regresa lentamente.',
    ),
    ExercisesCompanion.insert(
      name: 'Elevación de pantorrillas',
      description:
          'Elevación del talón para trabajar la musculatura de la pantorrilla.',
      primaryMuscle: 'calves',
      difficulty: 'beginner',
      movementPattern: 'calf_raise',
      exerciseType: 'strength',
      technique: 'Buscar un recorrido controlado y completo.',
      commonMistakes: 'Realizar rebotes rápidos.',
      considerations: 'Utilizar apoyo estable.',
      instructions: 'Desde una posición estable, eleva los talones y desciende lentamente.',
    ),
    ExercisesCompanion.insert(
      name: 'Press de banca',
      description: 'Empuje horizontal realizado con barra.',
      primaryMuscle: 'chest',
      difficulty: 'intermediate',
      movementPattern: 'horizontal_push',
      exerciseType: 'strength',
      technique: 'Mantener control de la barra y estabilidad de hombros.',
      commonMistakes: 'Rebotar la barra o perder la posición de los hombros.',
      considerations:
          'Utilizar un soporte seguro y asistencia cuando corresponda.',
      instructions: 'Tumbado en el banco, baja la barra controladamente hacia el pecho y empuja hasta extender los brazos.',
    ),
    ExercisesCompanion.insert(
      name: 'Press inclinado con mancuernas',
      description: 'Empuje inclinado utilizando mancuernas.',
      primaryMuscle: 'chest',
      difficulty: 'intermediate',
      movementPattern: 'horizontal_push',
      exerciseType: 'strength',
      technique: 'Mantener una trayectoria controlada y simétrica.',
      commonMistakes:
          'Descender sin control o mover excesivamente los hombros.',
      considerations: 'Elegir una inclinación y carga adecuadas.',
      instructions: 'Apoya la espalda en un banco inclinado, baja las mancuernas y empuja hacia arriba.',
    ),
    ExercisesCompanion.insert(
      name: 'Flexiones',
      description: 'Empuje horizontal utilizando el peso corporal.',
      primaryMuscle: 'chest',
      difficulty: 'beginner',
      movementPattern: 'horizontal_push',
      exerciseType: 'bodyweight',
      technique: 'Mantener el cuerpo alineado durante el movimiento.',
      commonMistakes: 'Dejar caer la cadera o separar demasiado los codos.',
      considerations: 'Modificar el apoyo para adaptar la dificultad.',
      instructions: 'Desde una posición de plancha, flexiona los codos para acercar el pecho al suelo y empuja para volver.',
    ),
    ExercisesCompanion.insert(
      name: 'Press militar con mancuernas',
      description: 'Empuje vertical utilizando mancuernas.',
      primaryMuscle: 'shoulders',
      difficulty: 'beginner',
      movementPattern: 'vertical_push',
      exerciseType: 'strength',
      technique: 'Mantener el tronco estable y controlar el recorrido.',
      commonMistakes: 'Compensar mediante una inclinación excesiva del tronco.',
      considerations: 'Elegir una carga que permita mantener estabilidad.',
      instructions: 'Coloca las mancuernas a la altura de los hombros y empújalas hacia arriba.',
    ),
    ExercisesCompanion.insert(
      name: 'Elevaciones laterales',
      description:
          'Ejercicio de aislamiento para la musculatura lateral del hombro.',
      primaryMuscle: 'shoulders',
      difficulty: 'beginner',
      movementPattern: 'shoulder_abduction',
      exerciseType: 'strength',
      technique: 'Utilizar un movimiento controlado y una carga ligera.',
      commonMistakes: 'Balancear el cuerpo o utilizar demasiado peso.',
      considerations: 'Evitar movimientos bruscos.',
      instructions: 'Eleva los brazos lateralmente hasta una posición cómoda y desciende lentamente.',
    ),
    ExercisesCompanion.insert(
      name: 'Fondos en paralelas',
      description: 'Empuje de tren superior realizado en paralelas.',
      primaryMuscle: 'triceps',
      difficulty: 'intermediate',
      movementPattern: 'vertical_push',
      exerciseType: 'strength',
      technique: 'Controlar el descenso y mantener estabilidad de hombros.',
      commonMistakes:
          'Descender sin control o perder la posición de los hombros.',
      considerations:
          'Utilizar asistencia si todavía no se domina el movimiento.',
      instructions: 'Sujétate a las paralelas, flexiona los codos para descender y empuja para volver.',
    ),
    ExercisesCompanion.insert(
      name: 'Jalón al pecho',
      description: 'Tirón vertical realizado en polea.',
      primaryMuscle: 'latissimus',
      difficulty: 'beginner',
      movementPattern: 'vertical_pull',
      exerciseType: 'strength',
      technique: 'Mantener el tronco estable y llevar los codos hacia abajo.',
      commonMistakes:
          'Tirar con impulso del cuerpo o llevar la barra detrás de la cabeza.',
      considerations: 'Utilizar una carga controlable.',
      instructions: 'Agarra la barra, inicia el movimiento con los codos hacia abajo y vuelve lentamente.',
    ),
    ExercisesCompanion.insert(
      name: 'Remo sentado en polea',
      description: 'Tirón horizontal realizado en polea baja.',
      primaryMuscle: 'upper_back',
      difficulty: 'beginner',
      movementPattern: 'horizontal_pull',
      exerciseType: 'strength',
      technique: 'Mantener el pecho estable y acercar los codos al cuerpo.',
      commonMistakes: 'Balancear el torso o encoger excesivamente los hombros.',
      considerations: 'Controlar el retorno de la carga.',
      instructions: 'Desde una posición estable, tira del agarre hacia el torso y regresa lentamente.',
    ),
    ExercisesCompanion.insert(
      name: 'Remo con mancuerna',
      description: 'Tirón horizontal unilateral realizado con mancuerna.',
      primaryMuscle: 'upper_back',
      difficulty: 'beginner',
      movementPattern: 'horizontal_pull',
      exerciseType: 'strength',
      technique: 'Mantener una base estable y controlar la trayectoria.',
      commonMistakes: 'Rotar excesivamente el torso.',
      considerations: 'Usar apoyo cuando sea necesario.',
      instructions: 'Apóyate sobre una superficie estable, lleva la mancuerna hacia la cadera y desciende lentamente.',
    ),
    ExercisesCompanion.insert(
      name: 'Dominadas asistidas',
      description:
          'Tirón vertical para trabajar espalda y brazos con asistencia.',
      primaryMuscle: 'latissimus',
      difficulty: 'intermediate',
      movementPattern: 'vertical_pull',
      exerciseType: 'strength',
      technique: 'Evitar balanceos y controlar la fase de descenso.',
      commonMistakes: 'Usar demasiado impulso.',
      considerations: 'Ajustar la asistencia al nivel del usuario.',
      instructions: 'Sujétate a la barra, realiza el tirón con control y desciende lentamente.',
    ),
    ExercisesCompanion.insert(
      name: 'Face pull',
      description: 'Tirón hacia el rostro para trabajar la musculatura posterior del hombro y espalda alta.',
      primaryMuscle: 'rear_delts',
      difficulty: 'beginner',
      movementPattern: 'horizontal_pull',
      exerciseType: 'strength',
      technique: 'Mantener los codos abiertos y controlar el recorrido.',
      commonMistakes: 'Usar una carga excesiva o compensar con el torso.',
      considerations: 'Priorizar el control del movimiento.',
      instructions: 'Tira del cable hacia el rostro separando las manos y regresa lentamente.',
    ),
    ExercisesCompanion.insert(
      name: 'Curl de bíceps',
      description: 'Flexión de codo realizada con mancuernas.',
      primaryMuscle: 'biceps',
      difficulty: 'beginner',
      movementPattern: 'elbow_flexion',
      exerciseType: 'strength',
      technique: 'Mantener los codos estables durante todo el movimiento.',
      commonMistakes: 'Balancear el torso para mover la carga.',
      considerations: 'Utilizar una carga que permita controlar la bajada.',
      instructions: 'Desde una posición estable, flexiona los codos para elevar las mancuernas y desciende lentamente.',
    ),
    ExercisesCompanion.insert(
      name: 'Curl martillo',
      description:
          'Curl con agarre neutro para bíceps y musculatura del antebrazo.',
      primaryMuscle: 'biceps',
      difficulty: 'beginner',
      movementPattern: 'elbow_flexion',
      exerciseType: 'strength',
      technique: 'Mantener las muñecas neutras y los codos estables.',
      commonMistakes: 'Mover excesivamente los hombros.',
      considerations: 'Evitar balanceos.',
      instructions: 'Mantén las palmas enfrentadas, flexiona los codos y regresa lentamente.',
    ),
    ExercisesCompanion.insert(
      name: 'Extensión de tríceps en polea',
      description: 'Extensión de codo realizada en polea.',
      primaryMuscle: 'triceps',
      difficulty: 'beginner',
      movementPattern: 'elbow_extension',
      exerciseType: 'strength',
      technique: 'Mantener los codos relativamente fijos.',
      commonMistakes: 'Mover los hombros para generar impulso.',
      considerations: 'Seleccionar una carga controlable.',
      instructions: 'Sujeta el agarre, extiende los codos hacia abajo y regresa de forma controlada.',
    ),
    ExercisesCompanion.insert(
      name: 'Extensión de tríceps por encima de la cabeza',
      description:
          'Extensión de codo realizada con la carga por encima de la cabeza.',
      primaryMuscle: 'triceps',
      difficulty: 'beginner',
      movementPattern: 'elbow_extension',
      exerciseType: 'strength',
      technique: 'Mantener el tronco estable y los codos controlados.',
      commonMistakes: 'Abrir excesivamente los codos o arquear la espalda.',
      considerations: 'Usar una carga moderada.',
      instructions: 'Coloca la carga sobre la cabeza, flexiona los codos y extiéndelos para regresar.',
    ),
    ExercisesCompanion.insert(
      name: 'Plancha',
      description: 'Ejercicio isométrico de estabilidad del tronco.',
      primaryMuscle: 'core',
      difficulty: 'beginner',
      movementPattern: 'core_anti_extension',
      exerciseType: 'core',
      technique: 'Mantener una línea estable desde hombros hasta cadera.',
      commonMistakes: 'Dejar caer la cadera o elevarla demasiado.',
      considerations: 'Reducir la duración si se pierde la posición.',
      instructions:
          'Apoya antebrazos y pies, activa el tronco y mantén la posición.',
    ),
    ExercisesCompanion.insert(
      name: 'Dead bug',
      description:
          'Ejercicio de control del tronco y coordinación de extremidades.',
      primaryMuscle: 'core',
      difficulty: 'beginner',
      movementPattern: 'core_anti_extension',
      exerciseType: 'core',
      technique: 'Mantener la zona lumbar estable durante el movimiento.',
      commonMistakes:
          'Mover las extremidades más allá de la capacidad de control.',
      considerations:
          'Reducir el rango de movimiento si se pierde estabilidad.',
      instructions: 'Desde tumbado boca arriba, mueve brazo y pierna contrarios manteniendo el tronco estable.',
    ),
    ExercisesCompanion.insert(
      name: 'Bird dog',
      description:
          'Ejercicio de estabilidad del tronco con movimiento contralateral.',
      primaryMuscle: 'core',
      difficulty: 'beginner',
      movementPattern: 'core_anti_rotation',
      exerciseType: 'core',
      technique: 'Evitar la rotación del tronco.',
      commonMistakes: 'Elevar demasiado las extremidades o mover la pelvis.',
      considerations: 'Realizar movimientos lentos.',
      instructions: 'Desde cuatro apoyos, extiende brazo y pierna contrarios y regresa controladamente.',
    ),
    ExercisesCompanion.insert(
      name: 'Crunch abdominal',
      description: 'Flexión controlada del tronco para trabajar la musculatura abdominal.',
      primaryMuscle: 'core',
      difficulty: 'beginner',
      movementPattern: 'core_flexion',
      exerciseType: 'core',
      technique: 'Realizar una flexión controlada sin tirar del cuello.',
      commonMistakes:
          'Impulsarse con las manos o realizar movimientos bruscos.',
      considerations: 'Detenerse si aparece molestia.',
      instructions: 'Tumbado boca arriba, flexiona el tronco de forma controlada y regresa lentamente.',
    ),
    ExercisesCompanion.insert(
      name: 'Pallof press',
      description:
          'Ejercicio de resistencia a la rotación realizado con cable o banda.',
      primaryMuscle: 'core',
      difficulty: 'beginner',
      movementPattern: 'core_anti_rotation',
      exerciseType: 'core',
      technique: 'Mantener el torso estable mientras se aleja el agarre.',
      commonMistakes: 'Rotar el tronco siguiendo la resistencia.',
      considerations: 'Ajustar la resistencia al nivel de control.',
      instructions: 'Colócate de lado a la resistencia, lleva el agarre al centro y extiende los brazos sin rotar.',
    ),
    ExercisesCompanion.insert(
      name: 'Mountain climbers',
      description: 'Ejercicio dinámico que combina estabilidad del tronco y movimiento de piernas.',
      primaryMuscle: 'core',
      difficulty: 'intermediate',
      movementPattern: 'locomotion',
      exerciseType: 'cardio',
      technique:
          'Mantener las manos estables y controlar la posición de la cadera.',
      commonMistakes: 'Rebotar o elevar demasiado la cadera.',
      considerations: 'Reducir la velocidad para mantener la técnica.',
      instructions: 'Desde una posición de plancha, lleva una rodilla hacia el pecho y alterna de forma controlada.',
    ),
    ExercisesCompanion.insert(
      name: 'Farmer walk',
      description: 'Desplazamiento transportando una carga en ambas manos.',
      primaryMuscle: 'forearms',
      difficulty: 'beginner',
      movementPattern: 'carry',
      exerciseType: 'strength',
      technique: 'Mantener postura erguida y pasos controlados.',
      commonMistakes: 'Encoger excesivamente los hombros o inclinar el torso.',
      considerations: 'Utilizar un espacio seguro para caminar.',
      instructions: 'Sujeta las cargas a los lados, mantén el tronco estable y camina durante la distancia indicada.',
    ),
    ExercisesCompanion.insert(
      name: 'Burpee',
      description: 'Movimiento dinámico de cuerpo completo.',
      primaryMuscle: 'full_body',
      difficulty: 'intermediate',
      movementPattern: 'locomotion',
      exerciseType: 'cardio',
      technique: 'Priorizar el control y adaptar la velocidad al nivel.',
      commonMistakes: 'Realizar los cambios de posición sin control.',
      considerations:
          'Utilizar una variante más sencilla cuando sea necesario.',
      instructions: 'Desde de pie, baja a una posición de apoyo, vuelve a incorporarte y finaliza extendiendo el cuerpo.',
    ),
    ExercisesCompanion.insert(
      name: 'Flexiones inclinadas',
      description: 'Flexión con las manos apoyadas en una superficie elevada para reducir la carga.',
      primaryMuscle: 'chest',
      difficulty: 'beginner',
      movementPattern: 'horizontal_push',
      exerciseType: 'bodyweight',
      technique: 'Mantener el cuerpo alineado de la cabeza a los talones y los codos a unos 45 grados del torso.',
      commonMistakes: 'Dejar caer la cadera o abrir demasiado los codos.',
      considerations: 'Es una progresión hacia las flexiones en el suelo: cuanto más baja la superficie, más difícil. Usa una superficie estable que no se mueva.',
      instructions: 'Apoya las manos en una superficie estable y elevada, baja el pecho hacia ella con el cuerpo recto y empuja para volver.',
    ),
    ExercisesCompanion.insert(
      name: 'Flexiones en pica',
      description: 'Flexión con la cadera elevada que desplaza la carga hacia los hombros.',
      primaryMuscle: 'shoulders',
      difficulty: 'intermediate',
      movementPattern: 'vertical_push',
      exerciseType: 'bodyweight',
      technique: 'Mantener la cadera alta y llevar la cabeza hacia el suelo entre las manos.',
      commonMistakes: 'Apoyar demasiado peso en la cabeza o separar los codos en exceso.',
      considerations: 'Es un ejercicio exigente para hombros y muñecas; si molesta, reduce el recorrido.',
      instructions: 'Colócate en forma de V invertida, flexiona los codos para acercar la cabeza al suelo y empuja para volver.',
    ),
    ExercisesCompanion.insert(
      name: 'Fondos en silla',
      description: 'Empuje de tríceps con las manos apoyadas en el borde de una silla o banco estable.',
      primaryMuscle: 'triceps',
      difficulty: 'beginner',
      movementPattern: 'vertical_push',
      exerciseType: 'bodyweight',
      technique: 'Mantener la espalda cerca de la silla y los hombros alejados de las orejas.',
      commonMistakes: 'Bajar demasiado, lo que sobrecarga los hombros, o alejar la cadera de la silla.',
      considerations: 'Usa una silla firme apoyada contra la pared. Si notas molestia en el hombro, reduce el recorrido.',
      instructions: 'Apoya las manos en el borde de la silla, flexiona los codos hacia atrás para bajar la cadera y empuja para subir.',
    ),
    ExercisesCompanion.insert(
      name: 'Remo invertido bajo mesa',
      description: 'Tirón horizontal tumbado bajo una mesa resistente, agarrando su borde.',
      primaryMuscle: 'upper_back',
      difficulty: 'intermediate',
      movementPattern: 'horizontal_pull',
      exerciseType: 'bodyweight',
      technique: 'Mantener el cuerpo recto y llevar el pecho hacia el borde de la mesa juntando los omóplatos.',
      commonMistakes: 'Dejar caer la cadera o tirar con los hombros hacia las orejas.',
      considerations: 'Úsalo solo con una mesa muy pesada y estable que no se desplace ni se incline. Si no tienes una segura, elige un remo con banda.',
      instructions: 'Túmbate bajo la mesa, agarra el borde con las manos, tira del pecho hacia arriba con el cuerpo recto y baja con control.',
    ),
    ExercisesCompanion.insert(
      name: 'Superman',
      description: 'Extensión de espalda tumbado boca abajo para fortalecer la espalda baja y los glúteos.',
      primaryMuscle: 'lower_back',
      difficulty: 'beginner',
      movementPattern: 'back_extension',
      exerciseType: 'bodyweight',
      technique: 'Elevar brazos y piernas de forma suave, manteniendo el cuello alineado con la columna.',
      commonMistakes: 'Hiperextender el cuello o elevar con tirones bruscos.',
      considerations: 'Haz un recorrido corto y controlado. Si notas dolor lumbar, detente.',
      instructions: 'Túmbate boca abajo con los brazos extendidos, eleva a la vez brazos y piernas unos centímetros, mantén un instante y baja.',
    ),
    ExercisesCompanion.insert(
      name: 'Peso muerto a una pierna',
      description: 'Bisagra de cadera sobre una sola pierna para trabajar femorales y glúteos y mejorar el equilibrio.',
      primaryMuscle: 'hamstrings',
      difficulty: 'intermediate',
      movementPattern: 'hinge',
      exerciseType: 'bodyweight',
      technique: 'Llevar la cadera hacia atrás con la espalda neutra mientras la otra pierna se extiende hacia atrás.',
      commonMistakes: 'Redondear la espalda o rotar la cadera hacia un lado.',
      considerations: 'Puedes apoyar una mano en una pared para equilibrarte y mantener la rodilla de apoyo ligeramente flexionada.',
      instructions: 'De pie sobre una pierna, inclina el tronco hacia delante llevando la otra pierna atrás y vuelve a la posición erguida.',
    ),
    ExercisesCompanion.insert(
      name: 'Sentadilla búlgara',
      description: 'Sentadilla unilateral con el pie trasero apoyado en una silla o banco.',
      primaryMuscle: 'quadriceps',
      difficulty: 'intermediate',
      movementPattern: 'lunge',
      exerciseType: 'bodyweight',
      technique: 'Mantener el tronco erguido y la rodilla delantera alineada con el pie.',
      commonMistakes: 'Colocar el pie delantero demasiado cerca de la silla o dejar que la rodilla colapse hacia dentro.',
      considerations: 'Usa una superficie estable a la altura de la rodilla y empieza con poco recorrido si te cuesta el equilibrio.',
      instructions: 'Apoya el empeine trasero en una silla, flexiona la rodilla delantera para descender y empuja con la pierna de delante para subir.',
    ),
    ExercisesCompanion.insert(
      name: 'Elevación de pantorrillas a una pierna',
      description: 'Elevación de talón sobre una sola pierna para aumentar la exigencia de la pantorrilla.',
      primaryMuscle: 'calves',
      difficulty: 'beginner',
      movementPattern: 'calf_raise',
      exerciseType: 'bodyweight',
      technique: 'Subir lo más alto posible sobre la punta del pie y bajar de forma lenta y controlada.',
      commonMistakes: 'Rebotar al bajar o doblar la rodilla de apoyo.',
      considerations: 'Apóyate ligeramente en una pared para mantener el equilibrio. Puedes hacerlo en el borde de un escalón para ganar recorrido.',
      instructions: 'De pie sobre una pierna, eleva el talón hasta quedar de puntillas y desciende lentamente.',
    ),
    ExercisesCompanion.insert(
      name: 'Patada de glúteo en cuadrupedia',
      description: 'Extensión de cadera a cuatro apoyos para activar el glúteo.',
      primaryMuscle: 'glutes',
      difficulty: 'beginner',
      movementPattern: 'hip_extension',
      exerciseType: 'bodyweight',
      technique: 'Mantener el abdomen activo y la espalda neutra mientras la pierna sube sin rotar la cadera.',
      commonMistakes: 'Arquear la zona lumbar o balancear el cuerpo para subir la pierna.',
      considerations: 'Prioriza el control y la contracción del glúteo antes que la altura de la pierna.',
      instructions: 'Apoya manos y rodillas, lleva una pierna hacia atrás y arriba y vuelve sin apoyar la rodilla en el suelo.',
    ),
    ExercisesCompanion.insert(
      name: 'Plancha lateral',
      description: 'Sostén lateral sobre el antebrazo para trabajar los oblicuos y la estabilidad del tronco.',
      primaryMuscle: 'core',
      difficulty: 'beginner',
      movementPattern: 'core_anti_lateral_flexion',
      exerciseType: 'core',
      technique: 'Mantener el cuerpo alineado de la cabeza a los pies con la cadera elevada.',
      commonMistakes: 'Dejar caer la cadera o rotar el torso hacia delante o hacia atrás.',
      considerations: 'Es un ejercicio de tiempo: si la app te pide repeticiones, anota los segundos mantenidos. Apoya la rodilla inferior si necesitas hacerlo más fácil.',
      instructions: 'Apoya el antebrazo en el suelo con los pies apilados o escalonados, eleva la cadera hasta alinear el cuerpo y mantén la posición.',
    ),
    ExercisesCompanion.insert(
      name: 'Jumping jacks',
      description: 'Salto coordinado abriendo y cerrando brazos y piernas para elevar el ritmo cardíaco.',
      primaryMuscle: 'full_body',
      difficulty: 'beginner',
      movementPattern: 'locomotion',
      exerciseType: 'cardio',
      technique: 'Aterrizar suave sobre la parte delantera del pie con las rodillas ligeramente flexionadas.',
      commonMistakes: 'Aterrizar con las piernas rígidas o perder el ritmo de la respiración.',
      considerations: 'Si necesitas bajar el impacto, haz la versión sin salto dando pasos laterales.',
      instructions: 'Parte de pie con los pies juntos, salta separando las piernas y elevando los brazos por encima de la cabeza, y vuelve a la posición inicial.',
    ),
    ExercisesCompanion.insert(
      name: 'Remo con banda',
      description: 'Tirón horizontal con banda elástica para trabajar la espalda media.',
      primaryMuscle: 'upper_back',
      difficulty: 'beginner',
      movementPattern: 'horizontal_pull',
      exerciseType: 'strength',
      technique: 'Juntar los omóplatos al tirar y mantener el pecho abierto y el tronco estable.',
      commonMistakes: 'Encogerse de hombros o ayudarse inclinando el tronco hacia atrás.',
      considerations: 'Ancla la banda en un punto firme y comprueba que no se suelte. Elige una resistencia que permita controlar el movimiento.',
      instructions: 'Con la banda anclada delante, sujeta los extremos, tira de ellos hacia el abdomen llevando los codos atrás y vuelve con control.',
    ),
    ExercisesCompanion.insert(
      name: 'Jalón con banda',
      description: 'Tirón vertical con banda anclada en alto para trabajar los dorsales.',
      primaryMuscle: 'latissimus',
      difficulty: 'beginner',
      movementPattern: 'vertical_pull',
      exerciseType: 'strength',
      technique: 'Llevar los codos hacia abajo y hacia las costillas sin inclinar el tronco.',
      commonMistakes: 'Tirar con los brazos en lugar de con la espalda o encogerse de hombros.',
      considerations: 'Ancla la banda en un punto alto y firme, como una barra bien fijada o un anclaje seguro de puerta.',
      instructions: 'Con la banda anclada arriba, sujeta los extremos con los brazos estirados, tira hacia el pecho llevando los codos abajo y vuelve despacio.',
    ),
    ExercisesCompanion.insert(
      name: 'Face pull con banda',
      description: 'Tirón hacia el rostro con banda para trabajar la parte posterior del hombro y la espalda alta.',
      primaryMuscle: 'rear_delts',
      difficulty: 'beginner',
      movementPattern: 'horizontal_pull',
      exerciseType: 'strength',
      technique: 'Separar las manos al tirar y llevar los codos altos y atrás.',
      commonMistakes: 'Usar demasiada resistencia y compensar echando el tronco hacia atrás.',
      considerations: 'Elige una resistencia ligera: es un ejercicio de control, no de fuerza máxima.',
      instructions: 'Con la banda anclada a la altura del rostro, tira de los extremos hacia la cara separando las manos y vuelve con control.',
    ),
    ExercisesCompanion.insert(
      name: 'Press de pecho con banda',
      description: 'Empuje horizontal con banda elástica anclada a la espalda.',
      primaryMuscle: 'chest',
      difficulty: 'beginner',
      movementPattern: 'horizontal_push',
      exerciseType: 'strength',
      technique: 'Mantener los codos ligeramente por debajo de los hombros y el tronco firme.',
      commonMistakes: 'Dejar que la banda tire de los hombros hacia delante al volver.',
      considerations: 'Asegura bien el anclaje detrás de ti: debe ser firme y estar a la altura del pecho.',
      instructions: 'Con la banda por detrás de la espalda, sujeta los extremos a la altura del pecho, empuja hacia delante hasta extender los brazos y vuelve con control.',
    ),
    ExercisesCompanion.insert(
      name: 'Curl de bíceps con banda',
      description: 'Flexión de codo con banda elástica pisada con los pies.',
      primaryMuscle: 'biceps',
      difficulty: 'beginner',
      movementPattern: 'elbow_flexion',
      exerciseType: 'strength',
      technique: 'Mantener los codos pegados al cuerpo y mover solo el antebrazo.',
      commonMistakes: 'Balancear el tronco para subir la banda.',
      considerations: 'Pisa la banda con ambos pies y ajusta la separación para cambiar la resistencia.',
      instructions: 'Pisa la banda, sujeta los extremos con las palmas hacia delante, flexiona los codos y baja lentamente.',
    ),
    ExercisesCompanion.insert(
      name: 'Extensión de tríceps con banda',
      description: 'Extensión de codo con banda anclada en alto para trabajar el tríceps.',
      primaryMuscle: 'triceps',
      difficulty: 'beginner',
      movementPattern: 'elbow_extension',
      exerciseType: 'strength',
      technique: 'Mantener los codos pegados a los costados y extender solo los antebrazos.',
      commonMistakes: 'Abrir los codos o inclinar el tronco hacia delante en exceso.',
      considerations: 'Ancla la banda en un punto alto y firme y comprueba que no se suelte.',
      instructions: 'Con la banda anclada arriba, sujeta los extremos a la altura del pecho y extiende los codos hacia abajo; vuelve despacio.',
    ),
    ExercisesCompanion.insert(
      name: 'Caminata lateral con banda',
      description: 'Desplazamiento lateral con una banda alrededor de las piernas para trabajar los glúteos medios.',
      primaryMuscle: 'glutes',
      difficulty: 'beginner',
      movementPattern: 'hip_abduction',
      exerciseType: 'strength',
      technique: 'Mantener las rodillas ligeramente flexionadas y los pies paralelos, sin juntar del todo las piernas.',
      commonMistakes: 'Dejar que las rodillas colapsen hacia dentro o inclinar el tronco.',
      considerations: 'Coloca la banda por encima de las rodillas o de los tobillos según la dificultad que busques.',
      instructions: 'Con la banda alrededor de las piernas, flexiona ligeramente las rodillas y da pasos laterales manteniendo la tensión.',
    ),
    ExercisesCompanion.insert(
      name: 'Press de suelo con mancuernas',
      description: 'Empuje de pecho con mancuernas tumbado en el suelo, sin necesidad de banco.',
      primaryMuscle: 'chest',
      difficulty: 'beginner',
      movementPattern: 'horizontal_push',
      exerciseType: 'strength',
      technique: 'Detener el recorrido cuando los codos toquen el suelo y empujar de forma controlada.',
      commonMistakes: 'Dejar caer los codos con fuerza contra el suelo o arquear la espalda.',
      considerations: 'El suelo limita el recorrido y protege el hombro. Empieza con una carga que puedas controlar.',
      instructions: 'Tumbado boca arriba con las rodillas flexionadas, baja las mancuernas hasta que los codos toquen el suelo y empuja hacia arriba.',
    ),
    ExercisesCompanion.insert(
      name: 'Dominadas',
      description: 'Tirón vertical colgado de una barra elevando el cuerpo con la fuerza de la espalda y los brazos.',
      primaryMuscle: 'latissimus',
      difficulty: 'advanced',
      movementPattern: 'vertical_pull',
      exerciseType: 'strength',
      technique: 'Iniciar el movimiento llevando los hombros hacia abajo y subir hasta que la barbilla supere la barra.',
      commonMistakes: 'Balancearse para impulsarse o descender de golpe sin control.',
      considerations: 'Es un ejercicio avanzado: si aún no puedes hacerlo, trabaja con el jalón con banda o las dominadas asistidas. Comprueba que la barra esté bien fijada.',
      instructions: 'Cuélgate de la barra con los brazos extendidos, tira hasta que la barbilla supere la barra y desciende con control.',
    ),
  ];
}
